#' Create weighted linear regression models for energy use data using time-of-week and outside air temperature as independent variables.
#'
#' \code{This function applies the hyperparamter, 'Weighting Factor', to the linear regressions generated by the function 'fit_TOWT_reg'.
#' It is a utility function for another kWMV function: 'model_with_TOWT'.
#' This function is adapted from work by LBNL: \url{https://lbnl-eta.github.io/RMV2.0/}}
#'
#' @param time_col time column of training data
#' @param eload_col eload column of training data
#' @param temp_col temp column of training data
#' @param pred_time_col time column of prediction data
#' @param pred_temp_col temp column of prediction data
#' @param timescale_days Numeric correspond to the timescale for weighting function.Default: NULL.
#' Change to improve accuracy of short term models.
#' @param interval_minutes Numeric for the interval period. Default: 15.
#' @param has_temp_knots_defined Boolean specifying whether the temp_knots are pre-defined or will be calculated by the algorithm
#' @param run_temperature_model Boolean specifying whether temperature should or should not be used in regression modeling.
#' @param equal_temp_segment_points Boolean specifying structure of temperature segments: equal number of points vs. equal segment length
#' @param temp_segments Numeric for number of temperature segments. Default: 6
#' @param temp_knots_value Vector specifying manually defined temperature knots.
#' @param has_operating_modes Boolean specifying whether the energy use profile has varying operating modes.
#' @param train_operating_mode_data dataframe with indicator variables for the various operating modes present in the model training period.
#' @param pred_operating_mode_data dataframe with indicator variables for the various operating modes present in the mdoel prediction period.
#' @param categories vector specifying names of the operating modes present.
#'
#' @return Weighted baseline and prediction matrices
#'
#' @export


create_TOWT_weighted_reg <- function(training_data = NULL, prediction_data = NULL,
                          timescale_days = NULL,
                          interval_minutes = NULL,
                          has_temp_knots_defined = c(TRUE, FALSE)
                          equal_temp_segment_points = c(TRUE, FALSE),
                          temp_segments_numeric = NULL,
                          temp_knots_value = NULL,
                          run_temperature_model = c(TRUE, FALSE)) {

  # Determine num_model_runs
  # TODO: move to model_with_TOWT



  num_model_runs <- weighted_dataframes$num_model_runs
  train_weight_vec <- weighted_dataframes$train_weight_vec
  pred_weight_vec <- weighted_dataframes$pred_weight_vec


  # For temperature segments and corresponding knots
  # TODO: move to model_with_TOWT

  has_temp_knots_defined <- match.arg(has_temp_knots_defined)
  equal_temp_segment_points <- match.arg(equal_temp_segment_points)
  run_temperature_model <- match.arg(run_temperature_model)

  temp_knots <- calculate_temperature_knots(training_data = training_data, has_temp_knots_defined = has_temp_knots_defined,
                                            temp_knots_value = temp_knots_value, temp_segments_numeric = temp_segments_numeric,
                                            equal_temp_segment_points = equal_temp_segment_points)

  # run Time-only and TOWT

  reg_out <- fit_TOWT_reg(training_data = training_data,
                           prediction_data = prediction_data,
                           temp_knots = temp_knots, train_weight_vec = train_weight_vec,
                           interval_minutes = interval_minutes,
                           run_temperature_model = run_temperature_model)


  # Creating weighting matrices for training and prediction data

  train_matrix <- matrix(NA, nrow = num_model_runs,
                           ncol = length(time_col))
  pred_matrix <- matrix(NA, nrow = num_model_runs,
                          ncol = length(pred_time_col))
  train_weight_matrix <- matrix(NA, nrow = num_model_runs,
                                  ncol = length(time_col))
  weight_matrix <- matrix(NA, nrow = num_model_runs,
                            ncol = length(pred_time_col))


  train_out <- reg_out$training
  train_matrix[row_index, ] <- train_out$training_load_pred
  train_weight_matrix[row_index, ] <- weight_vec
  training_model_occ_period <- reg_out$lm_results_occ_period
  training_model_unocc_period <- reg_out$lm_results_unocc_period

  pred_out <- reg_out$predictions
  pred_matrix[row_index, ] <- pred_out$pred_vec
  weight_matrix[row_index, ] <- weight_vec_pred


  # Applying th weighting matrix to baseline and prediction data

  final_pred_matrix <- apply(pred_matrix * weight_matrix, 2, sum) /
    apply(weight_matrix, 2, sum)
  final_train_matrix <- apply(train_matrix * train_weight_matrix, 2, sum) /
    apply(train_weight_matrix, 2, sum)

  output <- NULL
  output$time_vec <- pred_time_col
  output$final_pred_matrix <- final_pred_matrix
  output$pred_matrix <- pred_matrix
  output$weight_matrix <- weight_matrix
  output$train_time <- time_col
  output$final_train_matrix <- final_train_matrix
  output$temp_knots <- temp_knots
  output$training_model_occ_period <- training_model_occ_period
  output$training_model_unocc_period <- training_model_unocc_period

  return(output)
}
